//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace ET.Editor.SkillConfig
{

public sealed partial class SkillCanvasConfig :  Bright.Config.EditorBeanBase 
{
    public SkillCanvasConfig()
    {
            SkillConfigName = "";
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["NPBehaveId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  NPBehaveId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["BelongToSkillId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  BelongToSkillId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["SkillConfigName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  SkillConfigName = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {
            _json["NPBehaveId"] = new JSONNumber(NPBehaveId);
        }
        {
            _json["BelongToSkillId"] = new JSONNumber(BelongToSkillId);
        }
        {

            if (SkillConfigName == null) { throw new System.ArgumentNullException(); }
            _json["SkillConfigName"] = new JSONString(SkillConfigName);
        }
    }

    public static SkillCanvasConfig LoadJsonSkillCanvasConfig(SimpleJSON.JSONNode _json)
    {
        SkillCanvasConfig obj = new SkillConfig.SkillCanvasConfig();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonSkillCanvasConfig(SkillCanvasConfig _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// 对应技能图数据Id
    /// </summary>
    public long NPBehaveId { get; set; }

    /// <summary>
    /// 归属技能Id
    /// </summary>
    public long BelongToSkillId { get; set; }

    /// <summary>
    /// 资源名
    /// </summary>
    public string SkillConfigName { get; set; }

}
}
