//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET.cfg.UnitConfig
{
   
public partial class TbUnitAttribute
{
    private readonly Dictionary<int, UnitConfig.UnitAttributeConfig> _dataMap;
    private readonly List<UnitConfig.UnitAttributeConfig> _dataList;
    
    public TbUnitAttribute(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, UnitConfig.UnitAttributeConfig>();
        _dataList = new List<UnitConfig.UnitAttributeConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            UnitConfig.UnitAttributeConfig _v;
            _v = UnitConfig.UnitAttributeConfig.DeserializeUnitAttributeConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, UnitConfig.UnitAttributeConfig> DataMap => _dataMap;
    public List<UnitConfig.UnitAttributeConfig> DataList => _dataList;

    public UnitConfig.UnitAttributeConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UnitConfig.UnitAttributeConfig Get(int key) => _dataMap[key];
    public UnitConfig.UnitAttributeConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}