//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET.cfg.UnitConfig
{

public sealed partial class UnitResConfig :  Bright.Config.BeanBase 
{
    public UnitResConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        PrefabName = _buf.ReadString();
        PostInit();
    }

    public static UnitResConfig DeserializeUnitResConfig(ByteBuf _buf)
    {
        return new UnitConfig.UnitResConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// Prefab名
    /// </summary>
    public string PrefabName { get; private set; }

    public const int __ID__ = 290079958;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "PrefabName:" + PrefabName + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
