//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET.cfg.UnitConfig
{

public sealed partial class UnitAttributeConfig :  Bright.Config.BeanBase 
{
    public UnitAttributeConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        HP = _buf.ReadFloat();
        MP = _buf.ReadFloat();
        Attack = _buf.ReadFloat();
        MoveSpeed = _buf.ReadFloat();
        AttackSpeed = _buf.ReadFloat();
        PostInit();
    }

    public static UnitAttributeConfig DeserializeUnitAttributeConfig(ByteBuf _buf)
    {
        return new UnitConfig.UnitAttributeConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 生命值
    /// </summary>
    public float HP { get; private set; }
    /// <summary>
    /// 魔法值
    /// </summary>
    public float MP { get; private set; }
    /// <summary>
    /// 攻击力
    /// </summary>
    public float Attack { get; private set; }
    /// <summary>
    /// 移速
    /// </summary>
    public float MoveSpeed { get; private set; }
    /// <summary>
    /// 攻击速度
    /// </summary>
    public float AttackSpeed { get; private set; }

    public const int __ID__ = -1287398702;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "HP:" + HP + ","
        + "MP:" + MP + ","
        + "Attack:" + Attack + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "AttackSpeed:" + AttackSpeed + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
