//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET.cfg.SceneConfig
{
   
public partial class TbSceneBase
{
    private readonly Dictionary<int, SceneConfig.SceneBaseConfig> _dataMap;
    private readonly List<SceneConfig.SceneBaseConfig> _dataList;
    
    public TbSceneBase(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, SceneConfig.SceneBaseConfig>();
        _dataList = new List<SceneConfig.SceneBaseConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SceneConfig.SceneBaseConfig _v;
            _v = SceneConfig.SceneBaseConfig.DeserializeSceneBaseConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, SceneConfig.SceneBaseConfig> DataMap => _dataMap;
    public List<SceneConfig.SceneBaseConfig> DataList => _dataList;

    public SceneConfig.SceneBaseConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SceneConfig.SceneBaseConfig Get(int key) => _dataMap[key];
    public SceneConfig.SceneBaseConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}