//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET.cfg.LuBanSample
{
   
public partial class TbLuBanSample
{
    private readonly Dictionary<int, LuBanSample.LuBanSampleConfig> _dataMap;
    private readonly List<LuBanSample.LuBanSampleConfig> _dataList;
    
    public TbLuBanSample(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, LuBanSample.LuBanSampleConfig>();
        _dataList = new List<LuBanSample.LuBanSampleConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            LuBanSample.LuBanSampleConfig _v;
            _v = LuBanSample.LuBanSampleConfig.DeserializeLuBanSampleConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, LuBanSample.LuBanSampleConfig> DataMap => _dataMap;
    public List<LuBanSample.LuBanSampleConfig> DataList => _dataList;

    public LuBanSample.LuBanSampleConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LuBanSample.LuBanSampleConfig Get(int key) => _dataMap[key];
    public LuBanSample.LuBanSampleConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}