//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET.cfg.Unit
{
    public enum AttributeType
    {
        /// <summary>
        /// 生命
        /// </summary>
        HP = 1,
        /// <summary>
        /// 魔法
        /// </summary>
        MP = 2,
        /// <summary>
        /// 攻击力
        /// </summary>
        Attack = 3,
        /// <summary>
        /// 移速
        /// </summary>
        MoveSpeed = 4,
        /// <summary>
        /// 攻速
        /// </summary>
        AttackSpeed = 5,
    }
}
