//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace ET.Editor.SceneConfig
{

public sealed partial class SceneBaseConfig :  Bright.Config.EditorBeanBase 
{
    public SceneBaseConfig()
    {
            SceneName = "";
            SceneRecastNavDataFileName = "";
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["SceneName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  SceneName = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["SceneRecastNavDataFileName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  SceneRecastNavDataFileName = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {

            if (SceneName == null) { throw new System.ArgumentNullException(); }
            _json["SceneName"] = new JSONString(SceneName);
        }
        {

            if (SceneRecastNavDataFileName == null) { throw new System.ArgumentNullException(); }
            _json["SceneRecastNavDataFileName"] = new JSONString(SceneRecastNavDataFileName);
        }
    }

    public static SceneBaseConfig LoadJsonSceneBaseConfig(SimpleJSON.JSONNode _json)
    {
        SceneBaseConfig obj = new SceneConfig.SceneBaseConfig();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonSceneBaseConfig(SceneBaseConfig _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// 场景名
    /// </summary>
    public string SceneName { get; set; }

    /// <summary>
    /// 场景寻路数据文件名
    /// </summary>
    public string SceneRecastNavDataFileName { get; set; }

}
}
