//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET.cfg.SkillConfig
{

public sealed partial class SkillCanvasConfig :  Bright.Config.BeanBase 
{
    public SkillCanvasConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        NPBehaveId = _buf.ReadLong();
        BelongToSkillId = _buf.ReadLong();
        SkillConfigName = _buf.ReadString();
        PostInit();
    }

    public static SkillCanvasConfig DeserializeSkillCanvasConfig(ByteBuf _buf)
    {
        return new SkillConfig.SkillCanvasConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 对应技能图数据Id
    /// </summary>
    public long NPBehaveId { get; private set; }
    /// <summary>
    /// 归属技能Id
    /// </summary>
    public long BelongToSkillId { get; private set; }
    /// <summary>
    /// 资源名
    /// </summary>
    public string SkillConfigName { get; private set; }

    public const int __ID__ = -1467006160;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "NPBehaveId:" + NPBehaveId + ","
        + "BelongToSkillId:" + BelongToSkillId + ","
        + "SkillConfigName:" + SkillConfigName + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
